GET http://localhost:3001/api/ping

###

GET http://localhost:3001/api/patients

###

GET http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667

###

//adding new en entry
POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "some description",
  "date": "2026-01-27",
  "specialist": "Danaily",
  "diagnosisCodes": [0],
  "type": "HealthCheck",
  "healthCheckRating": 0 
}

###

POST http://localhost:3001/api/patients
content-type: application/json

{
  "name": "John Dou",
  "dateOfBirth": "2000-01-01",
  "ssn": "000000-000X",
  "gender": "male",
  "occupation": "Cantabria barrendero"
}

###
//getting diagnosis

GET http://localhost:3001/api/diagnoses